### ISSUE TITLE
chore: design a new logo for the project

### ISSUE THREAD

**Issue by damienwebdev** [faker-js/faker#101]

**Comment by JessicaSachs** [comment]
👋🏻 Looking like we have a few topic areas, all centered around disguises or animals that disguise themselves
1. Drama Masks
2. Superhero Masks
3. Sunglasses
4. Party Masks
5. Mustache + Hat
6. Mockingbirds
7. Pandas
8. Disguised Pandas

Here are some examples of each.
<img src="https://user-images.githubusercontent.com/2801156/149177138-32873624-113a-47b2-a8a5-38c2f47b8266.png" width="300"/>
<img src="https://user-images.githubusercontent.com/2801156/149178337-4bdd8dc4-7a2f-4637-a24d-e12b846e4ffc.png" width="300"/>
<img src="https://user-images.githubusercontent.com/2801156/149178620-2ad9d432-6914-48aa-a867-c1321ec2c971.png" width="300"/>
<img src="https://user-images.githubusercontent.com/2801156/149175367-225ae0ec-3448-4e59-82e3-dbd2322aa1f3.png" width="164"/>
<img src="https://user-images.githubusercontent.com/2801156/149175404-8dd5d7ce-c453-4a42-b6d0-8d0c92697b21.png"/>
<img src="https://user-images.githubusercontent.com/2801156/149175407-0268194b-d2f4-4bfd-acc5-32f33f561286.png"/>

**Comment by JessicaSachs** [comment]
We also have:
1. Panda 3 👍🏻  
<img src="https://user-images.githubusercontent.com/2801156/149181978-21cfcf17-45f2-4a8b-9e43-c3fc8cd26fa4.png" width="200"/>

**Comment by TechStudent11** [comment]
I'm not a designer but here's my concept. It's a minimalistic logo.

![Faker js concept](https://user-images.githubusercontent.com/76978184/149184402-14375514-137e-430d-9830-5cf4f765f08a.png)

**Comment by JessicaSachs** [comment]
K I'm gonna do the Panda. The witch panda might be a bit hard to pull off so I'm gonna try for _any_ Panda first 😅

**Comment by JessicaSachs** [comment]
The majority of people chose Panda. I did as much digging as I could for panda logos for purchase and found the following... (I couldn't find the witch) as well as one bird. I really like the bird if I were building a company.

Here's what I have:

<img width="240" alt="Screen Shot 2022-01-13 at 2 09 16 AM" src="https://user-images.githubusercontent.com/2801156/149285388-8d27232e-2f63-4669-91b4-046aaf9d242a.png">
<img width="240" alt="Screen Shot 2022-01-13 at 2 12 17 AM" src="https://user-images.githubusercontent.com/2801156/149285392-f63270bc-d55f-417d-a2fa-6b7be5dff6d7.png">
<img width="240" alt="Screen Shot 2022-01-13 at 2 12 56 AM" src="https://user-images.githubusercontent.com/2801156/149285394-5aa0309f-f375-4b1d-b831-f2709cf95bd1.png">
<img width="240" alt="Screen Shot 2022-01-13 at 2 13 45 AM" src="https://user-images.githubusercontent.com/2801156/149285401-94f995cd-04f1-41fa-a336-00b7bd4cd58f.png">
<img width="240" alt="Screen Shot 2022-01-13 at 2 24 35 AM" src="https://user-images.githubusercontent.com/2801156/149285404-409ada73-5ca5-4d67-b3cc-c7ead641c3f8.png">
<img width="240" alt="Screen Shot 2022-01-13 at 2 29 42 AM" src="https://user-images.githubusercontent.com/2801156/149285406-3da0942c-f069-46b6-991c-a403c2bf6959.png">
<img width="240" alt="Screen Shot 2022-01-13 at 2 29 47 AM" src="https://user-images.githubusercontent.com/2801156/149285415-33dd1d90-595a-4118-b5c8-bb85817a2403.png">
<img width="240" alt="Screen Shot 2022-01-13 at 2 13 19 AM" src="https://user-images.githubusercontent.com/2801156/149285397-e543dbb7-1b26-4699-8037-5925b806301b.png">


### 👍🏻 
<img width="240" alt="Screen Shot 2022-01-13 at 2 09 16 AM" src="https://user-images.githubusercontent.com/2801156/149285388-8d27232e-2f63-4669-91b4-046aaf9d242a.png">
### 👎🏻  
<img width="240" alt="Screen Shot 2022-01-13 at 2 12 17 AM" src="https://user-images.githubusercontent.com/2801156/149285392-f63270bc-d55f-417d-a2fa-6b7be5dff6d7.png">
### 😄 
<img width="240" alt="Screen Shot 2022-01-13 at 2 12 56 AM" src="https://user-images.githubusercontent.com/2801156/149285394-5aa0309f-f375-4b1d-b831-f2709cf95bd1.png">
### 🎉 
<img width="240" alt="Screen Shot 2022-01-13 at 2 13 45 AM" src="https://user-images.githubusercontent.com/2801156/149285401-94f995cd-04f1-41fa-a336-00b7bd4cd58f.png">
### 😕
<img width="240" alt="Screen Shot 2022-01-13 at 2 24 35 AM" src="https://user-images.githubusercontent.com/2801156/149285404-409ada73-5ca5-4d67-b3cc-c7ead641c3f8.png">
### ❤️ 
<img width="240" alt="Screen Shot 2022-01-13 at 2 29 42 AM" src="https://user-images.githubusercontent.com/2801156/149285406-3da0942c-f069-46b6-991c-a403c2bf6959.png">
### 🚀 
<img width="240" alt="Screen Shot 2022-01-13 at 2 29 47 AM" src="https://user-images.githubusercontent.com/2801156/149285415-33dd1d90-595a-4118-b5c8-bb85817a2403.png">
### 👀 
<img width="240" alt="Screen Shot 2022-01-13 at 2 13 19 AM" src="https://user-images.githubusercontent.com/2801156/149285397-e543dbb7-1b26-4699-8037-5925b806301b.png">

**Comment by JessicaSachs** [comment]
The majority of people chose Panda. I did as much digging as I could for panda logos for purchase and found the following... (I couldn't find the witch) as well as one new bird. I really like the bird if I were building a company, but because we're a devtool I think we can be more relaxed.

Here's what I have.
Same voting rules.

# 👍🏻 

<img width="120" alt="Screen Shot 2022-01-13 at 2 09 16 AM" src="https://user-images.githubusercontent.com/2801156/149285388-8d27232e-2f63-4669-91b4-046aaf9d242a.png">

# 👎🏻  

<img width="120" alt="Screen Shot 2022-01-13 at 2 12 17 AM" src="https://user-images.githubusercontent.com/2801156/149285392-f63270bc-d55f-417d-a2fa-6b7be5dff6d7.png">

# 😄 

<img width="120" alt="Screen Shot 2022-01-13 at 2 12 56 AM" src="https://user-images.githubusercontent.com/2801156/149285394-5aa0309f-f375-4b1d-b831-f2709cf95bd1.png">

# 🎉 

<img width="120" alt="Screen Shot 2022-01-13 at 2 13 45 AM" src="https://user-images.githubusercontent.com/2801156/149285401-94f995cd-04f1-41fa-a336-00b7bd4cd58f.png">

# 😕

<img width="120" alt="Screen Shot 2022-01-13 at 2 24 35 AM" src="https://user-images.githubusercontent.com/2801156/149285404-409ada73-5ca5-4d67-b3cc-c7ead641c3f8.png">

# ❤️ 

<img width="120" alt="Screen Shot 2022-01-13 at 2 29 42 AM" src="https://user-images.githubusercontent.com/2801156/149285406-3da0942c-f069-46b6-991c-a403c2bf6959.png">

# 🚀 

<img width="120" alt="Screen Shot 2022-01-13 at 2 29 47 AM" src="https://user-images.githubusercontent.com/2801156/149285415-33dd1d90-595a-4118-b5c8-bb85817a2403.png">

#  👀 

<img width="120" alt="Screen Shot 2022-01-13 at 2 13 19 AM" src="https://user-images.githubusercontent.com/2801156/149285397-e543dbb7-1b26-4699-8037-5925b806301b.png">

**Comment by JessicaSachs** [comment]
OK we now own one Magic Panda. Here's the zip of it:

[fakerjs-magic-panda.zip](https://github.com/faker-js/faker/files/7866139/fakerjs-magic-panda.zip)

It's purchased and licensed for non-profit use :+1:

**Comment by fncolon** [comment]
Panda magician seems cool!
