### ISSUE TITLE
this package was slowing down my jest tests

### ISSUE THREAD

**Issue by Alino** [faker-js/faker#1114]
I have been debugging my jest tests all day because they were failing due to timeouts, and sometimes passing but it took like 200 seconds sometimes to run few simple tests. Long story short, I have disabled creating my random mock data with faker and used hard-coded data instead. Now my jest runs in few seconds.

Note that it was not slowing down particular unit tests (they took few milliseconds), but the whole jest runtime took over hundreds of seconds. So it does not play nice with jest runner or whatever on windows 10 and also WSL.

**Comment by xDivisionByZerox** [comment]
Please provide a minimal test suite where this issue is present.
I'm using faker for personal and business tests in jest for fuzzing and have no problems at all with faker. [Jest itself is running terribly slow in windows machines](https://github.com/facebook/jest/issues/7631) (for me even with WSL), so please test your jest test suite on a linux VM and see if it happens there as well.

**Comment by Alino** [comment]
Sorry I can't spend more time on this by recreating a repo. But I can share the code change that has fixed my problem. Now my jest runs in 10 seconds instead of 200 seconds.

<img width="1313" alt="image" src="https://user-images.githubusercontent.com/763194/176319078-e3568b1b-dd82-4ddf-87ac-8587cf0b5f47.png">

**Comment by Shinigami92** [comment]
Try `@faker-js/faker/locale/en` and test again

**Comment by maximgeerinck** [comment]
> /locale/en

I can verify that this sped up my tests a lot!

**Comment by wodCZ** [comment]
I've isolated my tests slowdown to Faker too.
```
console.time('require');
const faker = require('@faker-js/faker');
console.timeEnd('require');
```
The require takes on average 1.6s on 2019 MacBook Pro

```
console.time('require');
const faker = require('@faker-js/faker/locale/en');
console.timeEnd('require');
```
Changing the import to `locale/en` reduces the require time to ~180ms on average.

**Comment by CookrC** [comment]
Hello, I am willing to start updating the documentation relating to this issue! If you do not mind, I would like to be assigned to this issue. 
Thanks!

**Comment by ST-DDT** [comment]
Thanks for your help.

**Comment by ST-DDT** [comment]
Note that we already have a page partially mentioning this, but the main usage page might need a hint for this as well and the localization page might need some more details.
https://fakerjs.dev/guide/localization.html

**Comment by gerardolima** [comment]
hey, @ST-DDT, first of all, thank you this library 🙌🏽 the documentation helps this issue, but I can bet they will only be read _after_ the performance issue becomes a problem and consumers will try to make sense out of it.

What would you think of fixing `en` locale for `@faker-js/faker` (ie: making it the same as `@faker-js/faker/locale/en`), and providing an alternate way to handle other locales? As for consumers, most of us do not expect to encounter performance issues related to loading a package to generate pseudo-random values. I believe this change to the default behaviour would be ok to most cases and would avoid performance costs related to edge cases.

**Comment by ST-DDT** [comment]
Hi @gerardolima thanks for your interest in this topic.

Default faker === fakerEn is already true

https://github.com/faker-js/faker/blob/1cf3991c180ddeb75253d1850f085147a04ee3bf/src/index.ts#L35

I wrote a separate issue that shows a potential solution to this:

- https://github.com/faker-js/faker/issues/3590
- https://github.com/faker-js/faker/issues/2667

Especially the derived nano-bound standalone module functions:

`const name = enFirstName()`

Which aim for an effective usage size of like 1-10KB vs the 600KB? it is now.

There might be other ways to speed up the process such as statically caching faker instead of reloading it for every test (file), but I havent looked into that.
