### ISSUE TITLE
Add more changelog sections

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#1244]
### Clear and concise description of the problem

The changelog.md does not contain hints regarding locale updates and refactors.
Especially the later are quite important as these could be considered (future) breaking changes.

### Suggested solution

Add more sections to the changelog.

### Alternative

Remove all of the commit prefixes except:

- feat
- fix
- chore
- docs
- test
- infra

### Additional context

- The changelog.md should be updated retrospectively.

**Comment by Shinigami92** [comment]
My assumption currently is that we moved away a bit from what `standard-version` expect
https://github.com/faker-js/faker/blob/e1905064091acc9e56a895bc2555803fc97bb08c/package.json#L80

So this package might only know `feat` and `fix` and ignores things like `chore` and custom created types

It ignores things like `chore` because these are not relevant for users to read
It doesn't know what a custom type like `locale` is and therefore cannot categories it below the headers `Features` and `Bug Fixes` (I mean how could it :shrug:)

So our assumption of "messing around" with scopes and types were a bit misleading and standardized tools could not handle it
I would suggest to move back to the standard / how it should be used, instead of crafting out custom types and scoped

**Comment by ST-DDT** [comment]
**Team decision**

- We want to have a section for locale updates and refactors
