### ISSUE TITLE
instead of random seed, use the seed based on package.json "name" field or folder name

### ISSUE THREAD

**Issue by capaj** [faker-js/faker#1507]
### Clear and concise description of the problem

currently I find myself always having to set the faker seed in every project manually. 
I could skip that if faker had a consistent seed based on data which does not change.

### Suggested solution

Change the default behaviour-instead of a random seed, use the package.json "name" field or parent folder name to calculate seed.

### Alternative

keed introducing 
```
    setupFiles: ['./test/vitestSetup.ts'],
```

```ts
import { faker } from '@faker-js/faker'

faker.seed(11) // this makes sure every run we get the same values from faker, which is nice to have for snapshots

```

in every project I need to test

### Additional context

Obviously this would have to be added in a new major version

**Comment by Shinigami92** [comment]
I'm not 💯% sure, but isn't `faker.seed` exactly for that use-case?
If we would do what you propose, other users would wonder about why the values are not random anymore 🤔

**Comment by ST-DDT** [comment]
I agree with @Shinigami92 here.
We have two usecases that we need to account for:

1. "Random data" so can check if it works for things you didnt exactly test for.
2. "Reproducible data" so that you can do snapshot tests etc to ensure everything looks exactly the same as last time.

We are good at the first part, but sadly faker is currently bad at the second step (if you keep faker up to date) as we update/extend locale data and improve our implementation.
Changing to a fixed seed by default would not fix the later usecase (as moving lines or updating faker would still change the result) but would make the first one harder (as you now have to set it to random each time).

IMO There are two solutions that could help you:

- add support for `any` seed so you can use `faker.seed(package_json.name)`
- add support for recording and replaying faker results

The former doesnt solve the underlying problem.
The later requires either per test setup (e.g. `recordedFaker = faker.recorded(path)`) or/and some glue code to the test framework to extract the test context from there e.g. a reverse `toMatchSnapshot()`. This is also a huge feature to implememt. Probably a major version on its own. Maybe requireing its own package for the test framework specific glue code.

Please let us know what you think about each of the suggestions and whether you have additional ideas.

**Comment by xDivisionByZerox** [comment]
Most likely somewhat related to #1499

**Comment by ST-DDT** [comment]
We have to conflicting requirements here:

1. Generating random values by default
2. Generating the same values every time

Since we already satisfy the first requirements and the scope of the later one is unclear (do you want the seed to be set once per test, once per file, or once per project). We have to reject this feature request and ask you to set the seed where you need it yourself.
