### ISSUE TITLE
Create a CLI for faker

### ISSUE THREAD

**Issue by ShivamJoker** [faker-js/faker#1565]
### Clear and concise description of the problem

It would be great if we could generate fake data in cli

### Suggested solution

Create a seprate CLI package

**Comment by Shinigami92** [comment]
Can you propose a CLI syntax for about 3+ examples of how you would call it?
And please describe your use-case.

**Comment by xDivisionByZerox** [comment]
@ShivamJoker You might want to get active on the [`faker-cli` repository](https://github.com/lestoni/faker-cli). They also have an outdated [npm package](https://www.npmjs.com/package/faker-cli).

**Comment by ShivamJoker** [comment]
@xDivisionByZerox it's outdated and doesn't have much data, it'll be great if we could have the cli officially.

My use case is mostly for sending data via the command line. eg. Bash script with curl

Synatx can be like:

```
faker name.first
```

**Comment by ST-DDT** [comment]
@ShivamJoker Could you please answer the question raised above?

> Can you propose a CLI syntax for about 3+ examples of how you would call it?

(Including ways to pass parameters+options)

Given that the question hasn't been answered already by anybody is an indicator that this feature appears to be of low interest for the community.

---

> it's outdated and doesn't have much data,

It uses Faker v7.3.0 which isnt that outdated.
If you wish to update it or need more methods, please also open an issue there or create a PR there.

**Comment by Shinigami92** [comment]
I contacted the maintainer via https://github.com/lestoni/faker-cli/issues/12

**Comment by xDivisionByZerox** [comment]
Since @lestoni never really replied to our offers we made, I started working on that in a side project.

@ShivamJoker, since you requested the feature:
How would you expect the CLI pacakge to work?

1. Download `@faker-js/cli`, which provides ots own version of faker internally. For example: you download `@faker-js/cli` v1, which has `@faker-js/faker` v8 installed under the hood. This would certainly be easier to implement, test, and maintain.
2. Download `@faker-js/cli` of any version AND `@faker-js/faker` as a peer dependency of the version you like (most likely with some restraines). This would certainly be really hard to develop, test, and maintain, but I can see this solution having infinitely more developer experience.

Obviously, I appreciate any tips, hints, and insights from any person. 🙌

**Comment by ShivamJoker** [comment]
Hey, I tried downloading it from npm but couldn't find it.

**Comment by xDivisionByZerox** [comment]
> Hey, I tried downloading it from npm but couldn't find it.

I just STARTED working on it. Since I asked you a fundamental question regarding the implementation, I'm nowhere close to finishing it.

**Comment by lestoni** [comment]
Hi @xDivisionByZerox @ShivamJoker I think you guy's came at the right time ? It did put a smile on my face :)  I would like to pass on faker-cli to you guys ? Sorry i didn't get back to you soon, had  major life events(since first contact but i have time now.  Where do i start ?

**Comment by lestoni** [comment]
Just joined the discord server!

> Hi @xDivisionByZerox @ShivamJoker I think you guy's came at the right time ? It did put a smile on my face :) I would like to pass on faker-cli to you guys ? Sorry i didn't get back to you soon, had major life events(since first contact but i have time now. Where do i start ?

**Comment by ST-DDT** [comment]
For CLI related feature requests/issues please create an issue here:

- https://github.com/faker-js/cli
