### ISSUE TITLE
Deprecate datatype module entirely and move all methods into other modules

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#1590]
We are adding the number module in #1122 and also #1341

- #1122
- #1341

Now we have some leftover methods in the datatype module but IMO it is not worth it to have a whole module for just these few methods.
I hope we can move these into other modules so we can get rid entirely of the datatype module.

**Comment by ST-DDT** [comment]
How about moving some stuff out of `helpers` as well?

- `faker.object` or `faker.record` (NEW)
  - `sample` (basically `faker.datatype.json()` without jsonifing the output)  <-- Not sure about that
  - `sampleJson` (`datatype.json` or maybe just drop it?)  <-- Not sure about that
  - `keyOf` (`helpers.objectKey`)
  - `valueOf` (`helpers.objectValue`)
- `faker.array` (NEW)
  - `sample` (`datatype.array`)
  - `elementOf` (`helpers.arrayElement`)
  - `elementsOf` (`helpers.arrayElements`)
  - `of` (`helpers.multiple`)
- `faker.date`
  - `sample` (`datatype.datetime`)
- `faker.boolean` (NEW)
  - `sample` (datatype.boolean) <-- Not sure about that

Maybe instead of `___Of` we could use `___From`.

**Comment by xDivisionByZerox** [comment]
> * `faker.object` or `faker.record` (NEW)
> [...]
> * `faker.array` (NEW)

An `Array` is nothing more than a specific `Object` in JS, so no to `faker.array`. Furthermore, all modules (with `helpers` as exception) should be able to generate a value from a specific function without requiring any input. The proposed methods `keyOf ` and `valueOf` always require an object as input. Thats why they ended up in `helpers` in the first place.

> - `faker.boolean`

I see why you propose this. But I have to say I really dislike having a module only for it to host one method. But to be fair, `boolean` is the one I'm unable to find a reasonable location as well.

**Comment by ST-DDT** [comment]
Currently, only two methods are left:

- [ ] [boolean](https://next.fakerjs.dev/api/datatype.html#boolean)
- [ ] [datetime](https://next.fakerjs.dev/api/datatype.html#datetime)

---

`datetime`: We can easily move it to the `date` module.

---

`boolean`: We could:

1. move it to helpers
   - ➖ Hard to find from code
2. create a tiny boolean module
   - ➕ Easier to find from code
   - ➖ Only a single method for the entire module
3. keep the tiny datatype module
   - ➖ Only a single method for the entire module
   - ➖ Unlikely to ever get more methods
4. or do something else entirely.

There doesn't seem to be a perfect solution for this for now.
I like 2 more than 1 and 3.

**Comment by matthewmayer** [comment]
I'd say a Boolean is a number 😀 have you considered faker.number.boolean?

**Comment by ST-DDT** [comment]
**Team Decision**

We will revive the datatype module with very simple methods for JS native datatypes only.
