### ISSUE TITLE
Add the Yoruba Language (yo_NG) as a new locale

### ISSUE THREAD

**Issue by mrsimi** [faker-js/faker#2341]
### Clear and concise description of the problem

As a developer using faker I want to be able to generate fake data that are native to the Yoruba Language. This will include person names, dates, and color. 

I will be willing to create a PR for it. 

### Suggested solution

Create a locale feature that is for the yoruba language under the yo_NG ISO

**Comment by matthewmayer** [comment]
Are new locales expected to hit the 10 👍 threshold like feature requests? Because other recent locale additions have not had to (Serbian, Danish, Esperanto etc). My feeling is if someone is willing to put in the work to do the PR and its verifiable (e.g. not so obscure a language that it doesn't appear on Google Translate) then it shouldnt have to hit a 10 vote minimum to be merged.

**Comment by ST-DDT** [comment]
FFR: yo_NG the language used in Nigeria.

---

Feel free to create the PR. But ~one PR per module/category please e.g. person, location. (Metadata doesn't count as module/category.)
Small sequential PRs are easier to review for us then large or parallel ones.

Thanks for your help.
