### ISSUE TITLE
Why not sort the API queries in the document?

### ISSUE THREAD

**Issue by XinYuanHaoFanPinChen** [faker-js/faker#2527]
### Clear and concise description of the problem

It is difficult to use without sorting

### Suggested solution

![Xnip2023-11-04_18-37-49](https://github.com/faker-js/faker/assets/37039204/f9528b57-1ced-4eaa-b4de-6b0ceda3ec5c)
![Xnip2023-11-04_18-38-13](https://github.com/faker-js/faker/assets/37039204/9f235f1c-3899-4a3c-b084-b94465e2abfa)

**Comment by xDivisionByZerox** [comment]
Just for clarification: 
You are suggesting that we  should only display modules in the API sidebar? Or are the faker constructors lower on your screenshot?

As an alternative, we could group the sidebar into core (faker constructors, util) and modules.

**Comment by matthewmayer** [comment]
Adding a extra separator before Airline would make it clearer that the rest are in alphabetical order

**Comment by XinYuanHaoFanPinChen** [comment]
Yes, the APIs in sidebar can be sorted alphabetically。🤔

**Comment by matthewmayer** [comment]
They already are, it's just that there are some special ones at the top and the bottom. Adding some extra separators or subheadings would clarify that.

**Comment by ST-DDT** [comment]
@LARVAIDE Are you interested in creating a PR to implement this?

**Comment by XinYuanHaoFanPinChen** [comment]
I'll give it a try。

**Comment by LARVAIDE** [comment]
It seems to have found a bug because the randomizer was not processed, resulting in no sorting.👀 @ST-DDT 
![Xnip2023-11-06_18-34-48](https://github.com/faker-js/faker/assets/37039204/67163b6a-d848-4160-b6d8-2ad9fc4979cf)
![Xnip2023-11-06_18-36-15](https://github.com/faker-js/faker/assets/37039204/a0fc813f-7372-4984-96e6-7e828ef66661)

**Comment by XinYuanHaoFanPinChen** [comment]
From the code, it can be seen that 'Faker', 'SimpleFaker', and 'Randomizer' have special rules, among which 'Randomizer' is not quite the same. Why is this necessary? @ST-DDT

**Comment by ST-DDT** [comment]
Because those are classes whereas the others are "Modules".

Faker has some internal classes, methods and other stuff, that should not be exposed in the api docs. Such as:

- *BaseModules (because those would be redundant)
- Helper functions and classes used inside the faker functions
- Locale definition interfaces and data
- MersenneTwister implementation

For that reason we select which data we wish to expose:

- API Classes/Interfaces: 'Faker', 'SimpleFaker', and 'Randomizer' (somewhat hardcoded)
- API Modules: Any class that fullfills  faker[some] = SomeModule`
- API Utilities (standalone functions): 'mergeLocales' (somewhat hardcoded)

**Comment by XinYuanHaoFanPinChen** [comment]
How about this display？
<img width="1439" alt="image" src="https://github.com/faker-js/faker/assets/37039204/0daa6331-16c1-49fb-bb8d-e0ea8a3d1597">

**Comment by matthewmayer** [comment]
That makes it look like Faker Core has its own page. But I don't think we have a link for that. Maybe Faker could be the "top level" item with others nested inside it?

**Comment by ST-DDT** [comment]
Or maybe use the following structure?

- API
  - Faker
  - SimpleFaker
  - ...
  - Modules
    - Airline
    - Animal
    - ...

**Comment by matthewmayer** [comment]
I feel like the Modules are the most important part for most users so they should not be nested too deep. It's only for advanced usage you really need to delve too much into the constructors, Randomizer etc.

Maybe just a `<hr>` to seperate the top section off without necessarily needing nesting or extra subheaders?

### API

- Overview
- Faker
- SimpleFaker
- Randomizer
- Utilities
---
- Airline
- Animal

**Comment by matthewmayer** [comment]
Alternatively stick with this proposal but add a new markdown page "Faker Core" with brief descriptions of what the 4 items inside are for?

<img width="1439" alt="image" src="https://github.com/faker-js/faker/assets/37039204/0daa6331-16c1-49fb-bb8d-e0ea8a3d1597">

**Comment by ST-DDT** [comment]
FakerCore will likely be a new type/interface/thing in v9. (DAO for locales, mersenne and config, not fixed yet)

How about the following structure:

- API
  - Faker
  - SimpleFaker
  - ...
- API Modules
  - Animal
  - ...

Alternatively, we could try the following

- API
  - Faker
  - SimpleFaker
  - ...
  - `<hr>`
  - Animal
  - ...

**Comment by xDivisionByZerox** [comment]
> Alternatively, we could try the following
> 
> - API
>   - Faker
>   - SimpleFaker
>   - ...
>   - `<hr>`
>   - Animal
>   - ...

I think that was the original idea.
