### ISSUE TITLE
faker.location.state() not working for sk

### ISSUE THREAD

**Issue by boubkerbribri** [faker-js/faker#3052]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] I am willing to provide a PR.

### Describe the bug

I'm trying to get `faker.local.state()` for local sk with a local fallback en_US, but I keep getting this error `[Error]: The locale data for 'location.state' aren't applicable to this locale.`

### Minimal reproduction code

```js
const {sk, Faker, en_US} = require('@faker-js/faker')

const faker = new Faker({locale: [sk, en_US]})
console.log(faker.location.state())
```

### Additional Context

<img width="994" alt="image" src="https://github.com/user-attachments/assets/546a5cbc-1dda-41b6-8c17-ddafa2dcaea8">

### Environment Info

```shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 291.94 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.16.0 - ~/.nvm/versions/node/v20.16.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.16.0/bin/yarn
    npm: 10.8.1 - ~/.nvm/versions/node/v20.16.0/bin/npm
  Browsers:
    Chrome: 127.0.6533.100
    Safari: 17.5
  npmPackages:
    @faker-js/faker: 8.4.1 => 8.4.1
```

### Which module system do you use?

- [x] CJS
- [ ] ESM

### Used Package Manager

npm

**Comment by Shinigami92** [comment]
Related to #2078

- #2078

I think you need to contribute values for https://github.com/faker-js/faker/blob/next/src/locales/sk/location/state.ts

**Comment by boubkerbribri** [comment]
Yeah of course, I can contribute to that but I need to understand well the behavior.

[On Documentation](https://fakerjs.dev/guide/localization.html#custom-locales-and-fallbacks), it says `In this example there are 5 locales. Each of these is checked in order, and the first locale which contains the requested data will be used`
So when I try to get state for this faker `const faker = new Faker({locale: [sk, en_US]})`  I expect to get one for en_US.

I think I'm missing something, if you could point that out please ?

**Comment by Shinigami92** [comment]
> I think I'm missing something, if you could point that out please?

Sure, just read the comment above that linked to the other PR. We introduced a specific `null` for some special cases so you wont get US states while using the sk locale.
states are a bit more realistically faked and so the intention is that you will get provided with states that are in that specific locale.
Additionally we added this behavior for exactly such a case right now, where a user comes up and found a locale that is not fully completed yet. And then we can kindly ask these contributors to help us, because a person like you are trained in sk locale, where as the internal maintainer team is mostly just german 😄

**Comment by ST-DDT** [comment]
The `null` means that `sk` doesn't have states/states aren't applicable to sk (or at least, that's what our data say).
`null` data are considered as "we have data here", but there is no valid way to fill them. (Similar to how there aren't any states on mars, there are likely also states that don't have separate countries)
It is likely wrong data in this case.

https://en.wikipedia.org/wiki/Slovakia#Administrative_divisions

Currently, en_US is missing the state definitions as well, en_US uses the fallback to en to provide these data which happen to be en_US, but en really should be either absent or cover more locales. So your fallback doesn't help in this case.

Since explicit "non-applicable" wins over any later fallbacks you have to adjust the order accordingly.

````ts
import { sk, Faker, en } from '@faker-js/faker';

const faker = new Faker({
  locale: [{ location: { state: en.location.state } }, sk],
});
console.log(faker.location.state());
````

> [On Documentation](https://fakerjs.dev/guide/localization.html#custom-locales-and-fallbacks), it says `In this example there are 5 locales. Each of these is checked in order, and the first locale which contains the requested data will be used`

It looks like we have to clarify this some more.

I think we additionally have to add a sections that explicitly explains what to do when you get the missing or non applicable data errors.

**Comment by xDivisionByZerox** [comment]
> Additionally we added this behavior for exactly such a case right now, where a user comes up and found a locale that is not fully completed yet

This is only partially correct.
`null` represents non applicable data (as the error suggests). When creating locales we somethimes find that some data is not available to specific locales due to concepts not existing. For example the locale AZ does not have the concept of person name prefixes, the english honkong locale doesn't have the concept of zipcodes or the russian locale doesnt know about person suffixes. In these cases we return an explicit null value to signal rhat these data is not known to the locale. People who work with these loves should never request these vales since the concept shouldn't exist there.

The problem is that faker has more than 60 locales and we are by far not exerts in all of them. If you find that we mistakenly made locale data non applicable although they are, please help us by providing meaningful related data to these locales.

**Comment by xDivisionByZerox** [comment]
I created #3053 to enhance the documentation. This issue can focus on aligning the locale data for `sk`.

**Comment by boubkerbribri** [comment]
Thank you all for your explanations. 
I'm more than happy to contribute but I should tell that I'm not an expert on SK locales. 
I was just trying to generate an address for more than 15 locals with the same function, sometimes I use state, sometimes I don't. That's why I used the fallback actually. but doesn't work that why so I understand.

**Comment by matthewmayer** [comment]
Note you probably want to just use fakerSK rather than using the constructor. That automatically will use sk, en-us and en in order.

**Comment by matthewmayer** [comment]
> Note you probably want to just use fakerSK rather than using the constructor. That automatically will use sk, en-us and en in order.

actually that won't work since the SK states are null, rather than omitted. i think Faker is incorrect about that - null should only be used where we know that data is not applicable - e.g. https://github.com/faker-js/faker/blob/next/src/locales/en_HK/location/postcode.ts is null because Hong Kong doesn't have postcodes. Slovakia does have first-level administrative regions, it's just they havent been filled in yet.

**Comment by ST-DDT** [comment]
@boubkerbribri I tried adding some documentation for these errors:

- https://github.com/faker-js/faker/pull/3055

Does that help you? Is it easy to understand? Is something missing?

**Comment by boubkerbribri** [comment]
> @boubkerbribri I tried adding some documentation for these errors:
> 
> * [docs(guide): add locale error handling sections #3055](https://github.com/faker-js/faker/pull/3055)
> 
> Does that help you? Is it easy to understand? Is somethign missing?

Yes, I think it's clear and understandable, it's what you said on the comment with more examples.
And the example works fine.
Thanks

**Comment by matthewmayer** [comment]
Part of https://github.com/faker-js/faker/issues/1977
