### ISSUE TITLE
Investigate why test address gps coords for non-metric sometimes fails

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#321]
### Describe the bug

[`218ae3a` (#285)](https://github.com/faker-js/faker/pull/285/commits/218ae3ace1085244a83ac32f56cea93f123cf389)

### Reproduction

comment in the outcommented code and see that it sometimes fails

### Additional Info

Not sure if the test is written wrongly or if the function really is broken

**Comment by ST-DDT** [comment]
The values from `faker.address.nearbyGPSCoordinate([0, 0])` are extremely bad.
I generated a thousand values.
And calculated their distance to the origin. `sqrt(lat² + long²)`
Actual:
Min: `0.05575°`, Avg: `0.05582°`, Max: `0.05588°`
Expected:
Min: `~0°`, Avg: `~0.075°`, Max: `~0.15°`

It looks like most of them are located on or near a circular line with a radius of `0.055` instead of a circular area with a radius of `0.150`. So we only use `~0.08%` of the available area.
