### ISSUE TITLE
Incorrect behavior of `name.firstName()` function

### ISSUE THREAD

**Issue by JoCat** [faker-js/faker#547]
### Describe the bug

When using the faker.name.firstName() function with a non-standard locale and without passing a gender value to the function, the name is still displayed in English.

### Reproduction

For example:
```js
import { faker } from '@faker-js/faker';

faker.locale = 'ru'; // Set another locale

const incorrectFirstName = faker.name.firstName(); // Jack (incorrect)
const correctFirstName = faker.name.firstName(0); // Евгений (correct)
const correctFirstName2 = faker.name.firstName(1); // Жанна (correct)
```

demo: https://stackblitz.com/edit/faker-js-demo-6fb7x2?file=index.ts

**Comment by JoCat** [comment]
thanks, maybe there is a problem in the code here:
https://github.com/faker-js/faker/blob/03c3d1156312153428f2db5649b24dd5fc046d43/src/name.ts#L38-L65
at least it differs from what is in the lastName and middleName functions, which work correctly

**Comment by Shinigami92** [comment]
I mean... that is quite the whole function except of 2-3 lines :wink: 
Maybe also have a look into https://github.com/faker-js/faker/pull/440

**Comment by Shinigami92** [comment]
Needs re-evaluation after #644 was merged

**Comment by JoCat** [comment]
Now displays Deprecation Warning
![image](https://user-images.githubusercontent.com/13483132/159767273-be931528-a490-4f0d-8ce7-ac3ed5be8c75.png)

**Comment by Shinigami92** [comment]
Yes, that is freshly implemented by us 🙂 
Please do not use `0` or `1` as parameter, but `'male'` or `'female'`

**Comment by JoCat** [comment]
> Yes, that is freshly implemented by us 🙂
> Please do not use 0 or 1 as parameter, but 'male' or 'female'

yes, didn't notice
It turns out the bug is still there

![image](https://user-images.githubusercontent.com/13483132/159795516-d1507568-31f7-4bc2-a13d-503843015d85.png)

**Comment by ST-DDT** [comment]
This issue is more complex then it looks like.

The basics:

- `female` is defined in `ru`
- `male` is defined in `ru`
- `generic` is defined in `en` (fallback language)
- If `generic` is not defined, it will use `female` or `male` randomly.

The possible solutions:
- Create/Configure a faker instance without the `en` fallback (Suggested workaround for now)
- Check whether `generic` is defined in the same language as `female` and `male`, if not treat it as not defined
  - This cannot be done via `faker.locales[faker.locale].name.xyz` because we wish to add support for multiple fallback languages in v7 (`en_AU_ocker` -> `en_AU` -> `en`).
    Thus we would have to add a new "trace" property similar to definitions, that returns the source locale of a property `faker.trace.name.firstname => 'en'`
- Create/Generate the `generic` source file automatically, if it is missing (`pnpm run generate:locales`)

**Comment by JoCat** [comment]
yes, it looks like when specifying localeFallback in ru, the code works correctly
https://stackblitz.com/edit/faker-js-demo-hxvbec?file=index.ts
although this is more like a temporary fix, and should not be taken as a full solution to the problem

If I understand correctly, the third option (indicate male and female names (surnames, patronymics) in the general array) is acceptable

**Comment by ST-DDT** [comment]
**Team decision**

Change datastructure:

name.female_first_name ->person.first_name.female

Example:
````ts
type Gendered = {
  female: string[]
  male: string[]
  generic: string[]
};
````

**Comment by matthewmayer** [comment]
Maybe I'm missing somethng, but isn't the simplest solution to add a first_name.ts file to locales which are missing one which simply concatenates the existing male_first_name and female_first_name lists?

Had a go at this in #1610

**Comment by ST-DDT** [comment]
If you add a new locale or change the locale config (for most of the parts in person), then you will encounter the bug again.
Changing the structure prevents that because then you have to either configure the entire block correctly or you will get compile time errors. You can either not define anything, define only generic, define only male and female or define all.

**Comment by ST-DDT** [comment]
The effect of the bug is fixed. The implementation/structure should still be adjusted accordingly.

**Comment by ST-DDT** [comment]
Further changes tracked via #1677
