### ISSUE TITLE
Use IANA standard for timezone

### ISSUE THREAD

**Issue by murraymichal** [faker-js/faker#734]
In documentation, please refer to standard you are using for generating timezones. 
E.g. `Asia/Rangoon` is not an official [IANA code](https://www.iana.org/time-zones), but is a "symlink" to `Asia/Yangon`. 
Thanks

**Comment by ST-DDT** [comment]
Could you please add a reference to the offending method?
I assume you are referring to 
https://fakerjs.dev/api/address.html#timeZone
Which uses a randomly chosen timezone.
https://github.com/faker-js/faker/search?q=Asia%2FRangoon&type=

The documentation has been regenerated since and now uses a different timezone.

So we only have to decide whether the method should return any timezone (official + aliases) or just official ones.

**Comment by murraymichal** [comment]
Yes. The same thing goes for the country name. We are using [ISO-3166](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes) names and faker is apparently using something different (possibly official UN names?). Please look at Korea as an example

ISO: Korea (the Democratic People's Republic Of)  - faker/UN: Democratic Peoples Republic of Korea (as short and formal)
ISO: Korea (the Republic Of)  - faker/UN: Republic of Korea (as short and formal)

**Comment by ST-DDT** [comment]
Thanks for bringing this to our attention.
We havent really touched these files since we took faker over. 
We will probably update these files in v6.2 along with the other locale files.
For now, we are focussing more on technical bugs.
-----------

Here some node packages that we could use as external sources, other suggestions are welcome:
Timezone: https://www.npmjs.com/package/tzdata
Country code: https://www.npmjs.com/package/country-codes-list

**Comment by sir-dunxalot** [comment]
Our app is also running to this issue. To access IANA timezones we use:

```js
import { rawTimeZones, RawTimeZone /* For Typescript */ } from '@vvo/tzdb';
```

**Comment by ST-DDT** [comment]
**Team decision**

use only official ones.
Extract locales from en,... and move to global/method scope.
