### ISSUE TITLE
Reorganize test file locations

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#911]
Move test files into src folder with `<module-name>.spec.ts` or reorganize the test folder with subfolders

**Comment by ST-DDT** [comment]
Is this still how we intend to implement this?

**Comment by Shinigami92** [comment]
> Is this still how we intend to implement this?

Not that sure. I'm in favor of staying in the `test` folder, so the test files don't accidentally bleed into `dist`.

**Comment by xDivisionByZerox** [comment]
> Is this still how we intend to implement this?

Let's discuss this in the next team meeting (?)

**Comment by matthewmayer** [comment]
i like having all the tests in one folder seperate to `src`, it makes it easy to search all the test code.

**Comment by ST-DDT** [comment]
**Pro**

- Tests are easier to find
- The structure of your test directory matches your src directory, because they are in one directory

**Con**

- Test files may bleed into dist
- Test snapshots folders in every source module folder
- Need a separate folder for common tests e.g. [locale-data.spec.ts](https://github.com/faker-js/faker/blob/next/test/locale-data.spec.ts)

**Team Decision**

- We keep the tests in a separate test folder.
- We can reopen this issue, if we want to reevaluate this design decision.
