### ISSUE TITLE
Change signature of hex

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#954]
### Clear and concise description of the problem

Currently by default `0x` is prefixed to the hex result

### Suggested solution

from:
```ts
hexadecimal(length: number)
```

to:

```ts
hexadecimal(length: number)

hexadecimal({ length: number, prefix: string = '' })
// or maybe better
hexadecimal({ length: number, withPrefix: boolean = false })
```

**Comment by import-brain** [comment]
[https://en.wikipedia.org/wiki/Hexadecimal#Distinguishing_from_decimal](Here) it says that there are a bunch of different prefixes in use across programming languages, not just `0x`, so I think the best way to implement this would be `hexadecimal({ length: number, prefix: string = '' })`, instead of having a `withPrefix` boolean param.
